// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gorkaio/gboy/pkg/cart (interfaces: CartInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCartInterface is a mock of CartInterface interface
type MockCartInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCartInterfaceMockRecorder
}

// MockCartInterfaceMockRecorder is the mock recorder for MockCartInterface
type MockCartInterfaceMockRecorder struct {
	mock *MockCartInterface
}

// NewMockCartInterface creates a new mock instance
func NewMockCartInterface(ctrl *gomock.Controller) *MockCartInterface {
	mock := &MockCartInterface{ctrl: ctrl}
	mock.recorder = &MockCartInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCartInterface) EXPECT() *MockCartInterfaceMockRecorder {
	return m.recorder
}

// Load mocks base method
func (m *MockCartInterface) Load(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load
func (mr *MockCartInterfaceMockRecorder) Load(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockCartInterface)(nil).Load), arg0)
}

// Read mocks base method
func (m *MockCartInterface) Read(arg0 uint16) byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(byte)
	return ret0
}

// Read indicates an expected call of Read
func (mr *MockCartInterfaceMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockCartInterface)(nil).Read), arg0)
}

// Write mocks base method
func (m *MockCartInterface) Write(arg0 uint16, arg1 byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Write", arg0, arg1)
}

// Write indicates an expected call of Write
func (mr *MockCartInterfaceMockRecorder) Write(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockCartInterface)(nil).Write), arg0, arg1)
}
