// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gorkaio/gboy/pkg/cart (interfaces: MemoryBankControllerInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMemoryBankControllerInterface is a mock of MemoryBankControllerInterface interface
type MockMemoryBankControllerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryBankControllerInterfaceMockRecorder
}

// MockMemoryBankControllerInterfaceMockRecorder is the mock recorder for MockMemoryBankControllerInterface
type MockMemoryBankControllerInterfaceMockRecorder struct {
	mock *MockMemoryBankControllerInterface
}

// NewMockMemoryBankControllerInterface creates a new mock instance
func NewMockMemoryBankControllerInterface(ctrl *gomock.Controller) *MockMemoryBankControllerInterface {
	mock := &MockMemoryBankControllerInterface{ctrl: ctrl}
	mock.recorder = &MockMemoryBankControllerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMemoryBankControllerInterface) EXPECT() *MockMemoryBankControllerInterfaceMockRecorder {
	return m.recorder
}

// Read mocks base method
func (m *MockMemoryBankControllerInterface) Read(arg0 uint16) byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(byte)
	return ret0
}

// Read indicates an expected call of Read
func (mr *MockMemoryBankControllerInterfaceMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockMemoryBankControllerInterface)(nil).Read), arg0)
}

// Write mocks base method
func (m *MockMemoryBankControllerInterface) Write(arg0 uint16, arg1 byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Write", arg0, arg1)
}

// Write indicates an expected call of Write
func (mr *MockMemoryBankControllerInterfaceMockRecorder) Write(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockMemoryBankControllerInterface)(nil).Write), arg0, arg1)
}
