// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cpu

import (
	"github.com/gorkaio/gboy/pkg/memory"
)

// Injectors from cpu_wire.go:

func InitializeCPU() (CPUInterface, error) {
	memoryInterface, err := memory.InitializeMemory()
	if err != nil {
		return nil, err
	}
	cpuInterface := New(memoryInterface)
	return cpuInterface, nil
}
