// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package gameboy

import (
	"github.com/gorkaio/gboy/pkg/cpu"
	"github.com/gorkaio/gboy/pkg/memory"
)

// Injectors from gameboy_wire.go:

func InitializeGameboy() (*Gameboy, error) {
	memoryInterface, err := memory.InitializeMemory()
	if err != nil {
		return nil, err
	}
	cpuInterface, err := cpu.InitializeCPU()
	if err != nil {
		return nil, err
	}
	gameboy, err := New(memoryInterface, cpuInterface)
	if err != nil {
		return nil, err
	}
	return gameboy, nil
}
