// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cart

// Injectors from loader_wire.go:

func InitializeLoader() (Loader, error) {
	loader := NewFileLoader()
	return loader, nil
}
