// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package memory

import (
	"github.com/gorkaio/gboy/pkg/cart"
)

// Injectors from memory_wire.go:

func InitializeMemory() (MemoryInterface, error) {
	loaderInterface := cart.InitializeCartLoader()
	memoryInterface, err := New(loaderInterface)
	if err != nil {
		return nil, err
	}
	return memoryInterface, nil
}
